blueprint:
  name: Z2M MQTT - RGBGenie 3008/3009 v3.2
  description: |
    Control RGBGenie ZB-3008/ZB-3009 через Z2M и MQTT.
    Полная интеграция с сохранением оригинальной логики управления.
  domain: automation
  input:
    mqtt_topic:
      name: "MQTT Topic"
      description: "Основной топик устройства (например: zigbee2mqtt/ZB-3009)"
      selector:
        text:
    modifier_input:
      name: "Сущность для модификатора"
      description: "Helper input_text для хранения текущего модификатора"
      selector:
        entity:
          domain: input_text
    light_1:
      name: "Light 1"
      selector:
        entity:
          domain: light
    light_2:
      name: "Light 2"
      selector:
        entity:
          domain: light
    light_3:
      name: "Light 3"
      selector:
        entity:
          domain: light
    force_brightness:
      name: "Фиксированная яркость"
      default: false
      selector:
        boolean:
    brightness:
      name: "Яркость по умолчанию"
      default: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    min_brightness:
      name: "Минимальная яркость"
      default: 1
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

trigger:
  - platform: mqtt
    topic: !input mqtt_topic
    value_template: "{{ value_json.action if value_json.action != '' }}"

variables:
  command: "{{ trigger.payload }}"
  payload: "{{ trigger.payload_json }}"
  current_modifier: "{{ states(input.modifier_input) | default('3') }}"
  light_entity: >
    {% if command in ['on','off'] %}
      {{ input.light_3 }}
    {% else %}
      {{ [input.light_1, input.light_2, input.light_3][(current_modifier|int(0)-1)] if current_modifier|int(0) in [1,2,3] else input.light_3 }}
    {% endif %}

blueprint:
  name: Z2M MQTT - RGBGenie 3008/3009 v3.1
  description: |
    Control RGBGenie ZB-3008/ZB-3009 через Z2M и MQTT.
    Полная интеграция с сохранением оригинальной логики управления.
  domain: automation
  input:
    mqtt_topic:
      name: "MQTT Topic"
      description: "Основной топик устройства (например: zigbee2mqtt/ZB-3009)"
      selector:
        text:
    modifier_input:
      name: "Сущность для модификатора"
      description: "Helper input_text для хранения текущего модификатора"
      selector:
        entity:
          domain: input_text
    light_1:
      name: "Light 1"
      selector:
        entity:
          domain: light
    light_2:
      name: "Light 2"
      selector:
        entity:
          domain: light
    light_3:
      name: "Light 3"
      selector:
        entity:
          domain: light
    force_brightness:
      name: "Фиксированная яркость"
      default: false
      selector:
        boolean:
    brightness:
      name: "Яркость по умолчанию"
      default: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    min_brightness:
      name: "Минимальная яркость"
      default: 1
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

trigger:
  - platform: mqtt
    topic: !input mqtt_topic
    value_template: "{{ value_json.action if value_json.action != '' }}"

variables:
  command: "{{ trigger.payload }}"
  payload: "{{ trigger.payload_json }}"
  current_modifier: "{{ states(input.modifier_input) | default('3') }}"
  light_entity: >
    {% if command in ['on','off'] %}
      {{ input.light_3 }}
    {% else %}
      {{ [input.light_1, input.light_2, input.light_3][(current_modifier|int(0)-1)] if current_modifier|int(0) in [1,2,3] else input.light_3 }}
    {% endif %}

action:
  - choose:
      - conditions: "{{ command matches 'recall_[123]' }}"
        sequence:
          - service: input_text.set_value
            target:
              entity_id: !input modifier_input
            data:
              value: "{{ command.split('_')[1] }}"
          
      - conditions: "{{ command in ['on','off'] }}"
        sequence:
          - service: light.toggle
            data:
              entity_id: "{{ light_entity }}"
              transition: 1
              brightness_pct: >
                {% if force_brightness and command == 'on' %}
                  {{ brightness }}
                {% else %}
                  {{ None }}
                {% endif %}

      - conditions: "{{ command == 'color_move' }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: "{{ light_entity }}"
              transition: 1
              xy_color: >
                [
                  {{ payload.action_color.x }},
                  {{ payload.action_color.y }}
                ]
          - service: input_text.set_value
            target:
              entity_id: !input modifier_input
            data:
              value: "3"

      - conditions: "{{ command in ['brightness_move_up','brightness_move_down'] }}"
        sequence:
          - repeat:
              count: 15
              sequence:
                - if:
                    - condition: template
                      value_template: "{{ command == 'brightness_move_up' }}"
                  then:
                    - service: light.turn_on
                      data:
                        entity_id: "{{ light_entity }}"
                        brightness_step_pct: 10
                        transition: 1
                  else:
                    - if:
                        - condition: template
                          value_template: >
                            {{ ((state_attr(light_entity, 'brightness')|int(0)/255*100)|round(0) -10) >= min_brightness }}
                      then:
                        - service: light.turn_on
                          data:
                            entity_id: "{{ light_entity }}"
                            brightness_step_pct: -10
                            transition: 1
                      else:
                        - service: light.turn_on
                          data:
                            entity_id: "{{ light_entity }}"
                            brightness_pct: "{{ min_brightness }}"
                            transition: 1
                - delay: "00:00:01"

      - conditions: "{{ command == 'color_temperature_move' }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: "{{ light_entity }}"
              color_temp: "{{ payload.action_color_temperature }}"
              transition: 1

mode: queued
max: 10

mode: queued
max: 10
